### ISSUE TITLE
Welcome page not linked to js files

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#51]
in branch feature/reg-login-ui-new
welcome page not using default layout --> js files are not there --> register and login modals not working.
anyone got alternative ways other than just hardcode the links in?

**Comment by dev-seahouse** [comment]
## there are some options :   
- option  1. define a welcome layout, extends welcome layout  
- option  2. extract our layout.blade.php into modular components inside layouts.e.g header, nav. footer, and srcripts section, then inside welcome just @include scripts -> recommended as layout.blade.php is a little bit big now (opinioned)  
- option 3. just hardcode in, because the purpose of a layout(master) page is to reduce reduce repeating code [](http://wiki.c2.com/?DontRepeatYourself)  , there is only one welcome page, so....it is really fine to break the rule one time

**Comment by eatedcookie** [comment]
k thanks i took option 3 in 59dcaf85d036e6314fc3509644d818fa7f53f3b3
